// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gedefApi.Models;

#nullable disable

namespace gedefApi.Migrations
{
    [DbContext(typeof(GedefDbContext))]
    [Migration("20220623142658_update tables")]
    partial class updatetables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("gedefApi.Models.Legajo", b =>
                {
                    b.Property<int>("LegajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegajoId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LegajoId");

                    b.ToTable("Legajos");
                });

            modelBuilder.Entity("gedefApi.Models.Question", b =>
                {
                    b.Property<int>("QnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QnId"), 1L, 1);

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opion2")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opion3")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opion4")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QnInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("QnId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("gedefApi.Models.TBA_BARCOS", b =>
                {
                    b.Property<int>("IDBAR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBAR"), 1L, 1);

                    b.Property<string>("ACTBAR")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("CODBAR")
                        .IsRequired()
                        .HasColumnType("nvachar(3)");

                    b.Property<string>("NOMBAR")
                        .IsRequired()
                        .HasColumnType("nvachar(50)");

                    b.Property<int>("NUMMAR")
                        .HasColumnType("int");

                    b.HasKey("IDBAR");

                    b.ToTable("TBA_BARCOS");
                });

            modelBuilder.Entity("gedefApi.Models.TBA_LEGAJO", b =>
                {
                    b.Property<int>("IDLEG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLEG"), 1L, 1);

                    b.Property<int>("CODPOS")
                        .HasColumnType("int");

                    b.Property<string>("CUIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LEGAJO")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RELEVO")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IDLEG");

                    b.ToTable("TBA_LEGAJOS");
                });

            modelBuilder.Entity("gedefApi.Models.TBA_PLANTILLAS", b =>
                {
                    b.Property<int>("IDPLA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPLA"), 1L, 1);

                    b.Property<string>("CAPITAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("COCINERO")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CODPLA")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CODROLXBAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MARINCUB1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NOMBAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NUMMAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PRIMEROF")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDPLA");

                    b.ToTable("TBA_PLANTILLAS");
                });

            modelBuilder.Entity("gedefApi.Models.TBA_ROLXBAR", b =>
                {
                    b.Property<int>("IDROLXBAR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDROLXBAR"), 1L, 1);

                    b.Property<string>("CAPITAN")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("COCINERO")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("CODBAR")
                        .IsRequired()
                        .HasColumnType("nvachar(3)");

                    b.Property<string>("CODROLXBAR")
                        .IsRequired()
                        .HasColumnType("nvachar(3)");

                    b.Property<string>("JEFEMAQUINA")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("MARINCUB1")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("MARINPLA1")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.Property<string>("PRIMEROF")
                        .IsRequired()
                        .HasColumnType("nvachar(1)");

                    b.HasKey("IDROLXBAR");

                    b.ToTable("TBA_ROLXBAR");
                });

            modelBuilder.Entity("gedefApi.Models.TBA_USUARIOS", b =>
                {
                    b.Property<int>("USUARIOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USUARIOID"), 1L, 1);

                    b.Property<string>("CATEGORIA")
                        .IsRequired()
                        .HasColumnType("nvachar(50)");

                    b.Property<string>("CONTRASEÑA")
                        .IsRequired()
                        .HasColumnType("nvachar(50)");

                    b.Property<string>("USUARIO")
                        .IsRequired()
                        .HasColumnType("nvachar(50)");

                    b.HasKey("USUARIOID");

                    b.ToTable("TBA_USUARIOS");
                });
#pragma warning restore 612, 618
        }
    }
}
